export const
    LOADER_PROGRESS = 'LOADER_PROGRESS',
    LOADER_RAZ = 'LOADER_RAZ';

export const
    SOUND_SET = 'SOUND_SET',
    SOUND_RAZ = 'SOUND_RAZ';

export const
    HISTORY_SCENE = 'HISTORY_SCENE',
    HISTORY_ERROR_SET = 'HISTORY_ERROR_SET',
    HISTORY_ERROR_RAZ = 'HISTORY_ERROR_RAZ',
    HISTORY_RAZ = 'HISTORY_RAZ';
